find_package(Qt5Core REQUIRED)
set(QT_INCLUDES "$${Qt5Core_INCLUDE_DIRS}")
set(QT_LIBRARIES "${Qt5Core_LIBRARIES}")
set(QT_DEFINITIONS "${Qt5Core_DEFINITIONS}")

include_directories(SYSTEM "${QT_INCLUDES} ${SYSTEM}")
add_definitions(${QT_DEFINITIONS})

set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR "ON")
